### ISSUE TITLE
The PERCY_TOKEN environment variable is missing.

### ISSUE THREAD

**Issue by vivekbwaj** [percy/storybook-action#18]
Windows 10 :
I am following this tutorial https://docs.percy.io/docs/storybook-tutorial.
I forked this repository https://github.com/percy/example-storybook-for-react.git. I cloned it in my local and set the PERCY_TOKEN. I do not get any error at this point but when I run 'npm run snapshot' 
`
Error:  Error: The PERCY_TOKEN environment variable is missing.
    at Object._callee$ (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\@percy-io\percy-storybook\lib\cli.js:79:19)
    at tryCatch (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\core-js\library\modules\_export.js:36:28)
    at Object.<anonymous> (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
    at Object.run (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\@percy-io\percy-storybook\lib\cli.js:128:17)
    at Object.<anonymous> (C:\Automation\demos\storybookTut\exampleStorybook_Forked\example-storybook-for-react\node_modules\@percy-io\percy-storybook\bin\percy-storybook.js:4:4)
`

**Comment by wwilsman** [comment]
Judging from the linked issue, this might be due to action secrets not being shared with forks. This is a GitHub security feature that you can disable in the project's settings but opens up forks to have access to your env secrets.

I'm going to close this since there isn't anything we can do in this action, but feel free to continue the discussion if you think this is a different issue.
